import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BugTracker',
  description: 'Generated by create next app',
  icons: {
    icon: "https://icons8.com/icon/9227/bug",
    apple: "https://icons8.com/icon/9227/bug"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
